/* VENDORED from LearningLeagues-Lib @ 6be46f668e976833eef4c71b2161269753dc2c13 (dist/ll-lib.jsx).
 * GENERATED twice over: by `pnpm dist:build`, then pinned here by
 * `node scripts/vendor-dist.ts --write`. Never edit in this repository —
 * bump the pin by re-running the vendoring at a new lib commit. */

/* GENERATED by `pnpm dist:build` (scripts/generate-dist.ts): the real
 * component sources, types stripped, JSX preserved (esbuild), exposed as
 * window.LL globals for a buildless host (React UMD + Babel standalone).
 * Do not edit; edit the component .tsx sources and regenerate. */

// ── Button (button) ──
function Button({
  variant = "primary",
  href,
  type = "button",
  onClick,
  children
}) {
  const className = `ll-button ll-button--${variant}`;
  if (href !== void 0) {
    return <a className={className} href={href} onClick={onClick}>
        {children}
      </a>;
  }
  return <button className={className} type={type} onClick={onClick}>
      {children}
    </button>;
}

window.LL = Object.assign(window.LL || {}, { Button });
