/* VENDORED from LearningLeagues-Lib @ 8dd599df1b1c9bf61f9daa4996261eaf81c94f05 (dist/ll-lib.jsx).
 * GENERATED twice over: by `pnpm dist:build`, then pinned here by
 * `node scripts/vendor-dist.ts --write`. Never edit in this repository —
 * bump the pin by re-running the vendoring at a new lib commit. */

/* GENERATED by `pnpm dist:build` (scripts/generate-dist.ts): the real
 * component sources, types stripped, JSX preserved (esbuild), exposed as
 * window.LL globals for a buildless host (React UMD + Babel standalone).
 * Do not edit; edit the component .tsx sources and regenerate. */

// ── Button (button) ──
function Button({
  variant = "primary",
  href,
  type = "button",
  onClick,
  children
}) {
  const className = `ll-button ll-button--${variant}`;
  if (href !== void 0) {
    return <a className={className} href={href} onClick={onClick}>
        {children}
      </a>;
  }
  return <button className={className} type={type} onClick={onClick}>
      {children}
    </button>;
}

// ── Callout (callout) ──
const LABELS = {
  key: "Key concept",
  pro: "Pro tip",
  trap: "Trap"
};
function Callout({ type, title, children }) {
  return <article className={`ll-callout ll-callout--${type}`}>
      <span className="ll-callout-tag">
        <i className="ll-callout-glyph" aria-hidden="true" />
        {LABELS[type]}
      </span>
      {title ? <h3 className="ll-callout-title">{title}</h3> : null}
      <div className="ll-callout-body">{children}</div>
    </article>;
}

window.LL = Object.assign(window.LL || {}, { Button, Callout });
